### ISSUE TITLE
Demo-Link redirects to Wiki

### ISSUE THREAD

**Issue by TheTechRobo** [pluck-cms/pluck#103]
In the readme the Link to the Demo-Link is broken.

**Comment by BSteelooper** [comment]
We moved the website to solely the GitHub wiki. therefor we now have no demo environment. 

I removed the link

**Comment by billcreswell** [comment]
Softaculous offers a demo pluck install https://softaculous.com/demos/Pluck

**Comment by BSteelooper** [comment]
Thanks @billcreswell I didn't know that. I have updated the readme file.
