### ISSUE TITLE
Security issue found

### ISSUE THREAD

**Issue by newb3ast** [pluck-cms/pluck#120]
Hi 

I just want to ask to whom I can address a security issue here in pluck. Thanks!

**Comment by BSteelooper** [comment]
Per GitHub Policy and recommendation we have a security.md file which contains our disclose emailadres
https://github.com/pluck-cms/pluck/blob/master/SECURITY.md

**Comment by newb3ast** [comment]
Hi @BSteelooper 

Thank you for the reply. I've been sending the report for about a year. I'll send an email again regarding the vulnerability I found. By the way, in case you have a lot of email queries, I'll attach the link to the reported findings on huntr.dev.

https://huntr.com/bounties/a2bd1667-945e-439d-8d7d-ea876b128314
