### ISSUE TITLE
Upgrade form 4.7 to 4.7.3

### ISSUE THREAD

**Issue by FransHeitkamp** [pluck-cms/pluck#23]
This is not issue but a question. I didn't know where to post it so I am doing it here,

I have installed Pluck 4.7 and have built our website. How do I upgrade to 4.7.3 without having to rebuild ten website from scratch.

**Comment by billcreswell** [comment]
There is not currently an automated way to update your versions. 

I do mine the old fashioned way the usual - back up my data directory, and separately backing up my whole site, and do a fresh install, reinserting my pages, themes and modules.

**Comment by Filisko** [comment]
Well, I do the same as @billcreswell, Is not that difficult really.

**Comment by FransHeitkamp** [comment]
Hi Guys,

Thanks a lot for your support. This is helpful.

**Comment by Filisko** [comment]
You're welcome @FransHeitkamp !

**Comment by billcreswell** [comment]
Thanks for all your help and contributions, @Filisko
