### ISSUE TITLE
Can't access Pluck: index.php redirects somewhere, get 404 or DNS error

### ISSUE THREAD

**Issue by Lesik** [pluck-cms/pluck#25]
I installed Pluck on a webserver (not mine, but I'm allowed to use parts of it). I choosed pluck because it only needed PHP (no Ruby/ASP/SQL, which I do not have the permission to install). I have SFTP and (no-root) SSH access.
I went through the installation process, set the permissions correctly. The admin panel works fine (altough it looks a bit weird, but that's not the major problem here). But when I try to see the site it redirects me somewhere.

Let's say I have Pluck installed in http://domain.tld/subfolder/pluck.

If I click "view site" in the menu of the admin panel, I get redirected to http://domain.tld/subfolder/pluck/g/ which doesn't exist, resulting in a 404 error.
If I click "take a look at your website" in the admin panel, it sends me to http://domain.tld/subfolder/pluck/index.php, which then redirects me to http://domain.tldg/ (note the g after the tld, e.g. google.com → google.comg) which results in a DNS error.

So I can't access the website. I followed the installation guide (https://github.com/pluck-cms/pluck/wiki/Installation-guide) and checked the FAQ, there doesn't seem to be some config I forgot to edit or something similar. Any idea why this happens?

**Comment by Lesik** [comment]
Forgot to mention, it's Pluck 4.7.3.

I think the problem is in `data/inc/variables.all.php`. In this file, `SITE_URL` is defined incorrectly. If I manually set `SITE_URL` to `/subfolder/pluck`, Pluck seems to work. Pluck tries to auto-generate that variable, there must be some bug somewhere, because it generates `g` instead.

**Comment by BSteelooper** [comment]
Dear @Lesik, I know it is a while back. I am looking into this issue at this moment, but cannot reproduce it :( can you please try it again with the latest 4.7.4 dev version? You can find it her: https://github.com/pluck-cms/pluck/releases 

Thank you.

**Comment by Lesik** [comment]
It's an interesting bug though, isn't it? Just randomly adding `g`s to URLs?
