### ISSUE TITLE
Some German translations are missing

### ISSUE THREAD

**Issue by vavoor** [pluck-cms/pluck#28]
Hi,

some of the German translations are missing, as you easily can see when comparing en.php and de.php. I'd volunteer to provide them if somebody could tell me how to become a contributor.

Cheers,
Gerd

**Comment by vavoor** [comment]
Issued a pull request.

**Comment by billcreswell** [comment]
Merged request

**Comment by vavoor** [comment]
Thanks, Bill!

Gerd
