### ISSUE TITLE
Would like to be able to write page content in Markdown

### ISSUE THREAD

**Issue by vavoor** [pluck-cms/pluck#32]
Actually I'd even work on this, but I wonder with whom this should be discussed. Who needs to agree on releases, contents, etc. Is there some discussion group?

Thanks,
Gerd

**Comment by billcreswell** [comment]
We are informal here. Submit it, we will do some testing before the next
release.

We do some discussion on the phphelp forum, if you want, or here in the
comments works too.

For this case, I love markdown, but Pluck is intended to just work simply
for any user.

This could end up as a compatibility break, It may be the kind of thing to
fork Pluck, and try it out, see how it will work first.

Perhaps a simple gui markdown replacement could used in place of what is
there.

I

Actually I'd even work on this, but I wonder with whom this should be
discussed. Who needs to agree on releases, contents, etc. Is there some
discussion group?

Thanks,
Gerd

—
Reply to this email directly or view it on GitHub
<https://github.com/pluck-cms/pluck/issues/32>.

**Comment by billcreswell** [comment]
Pluck Forum: http://www.phphelp.com/forum/pluck-cms/
Planning Wiki https://github.com/pluck-cms/pluck/wiki/Planning
