### ISSUE TITLE
module

### ISSUE THREAD

**Issue by thehosting4you** [pluck-cms/pluck#33]
Hello
Who can help me with a guestbook?
M.v.g. André

**Comment by billcreswell** [comment]
Did you have something in mind?
I haven't checked out any of these examples, as I've never had a use for a guestbook: http://web-design.lovetoknow.com/Free_Guestbooks_for_Websites

There is also an older version in the Ekyo Powerpack that I could update for 4.7
http://en.pluck.ekyo.pl/2.Super_Pluck_Power_Pack.php

**Comment by thehosting4you** [comment]
Hello,

I would like to use that guest but could get a check in so the admin who must approve Voorda the message comes on the website.

With Friendly Greeting André

**Comment by billcreswell** [comment]
This is really a request for a new module, rather than an issue with pluck.
