### ISSUE TITLE
Multi Themes Not Working

### ISSUE THREAD

**Issue by 2braincells2go** [pluck-cms/pluck#35]
Greetings!

Testing Pluck for use in classroom project and have couple of issues. The most pressing issue is multi theme. Have the module installed and not working for me.

I go to page and under "other options" choose different theme and save. It defaults back to active main theme after save?

No errors thrown on page or dev console. All directories/files writable.

See that the demo site at softaculous does work when applying new theme to page, so wondering if some security setting or???

One other think if anyone knows: Can you use friendly URL's instead of Pluck/?file=tester

Thanks!

**Comment by billcreswell** [comment]
The softaculous demo worked.

When you edit the page, you can select a different theme.

**Comment by billymail** [comment]
'SEO Friendly Urls use the SEO Plugin and requires an htaccess file.
https://github.com/pluck-cms/seo-module

**Comment by 2braincells2go** [comment]
Thanks Bill.

Yes the softaculous demo worked as tried it before coming here and asking:) My test site does not. Wondering if some type of security settings I could check on server, not switching themes when I choose different one.

My bad, had seo plugin installed but totally forgot to change htaccess file.

**Comment by billcreswell** [comment]
Multithemes should write:
<?php
$title = 'OldStyle';
$seoname = 'oldstyle';
$content = '<p>OldStyle</p>';
$hidden = 'no';
$p_theme = 'oldstyle';
?>

**Comment by thehosting4you** [comment]
Hello,

I have the same problem that I can not use a different template on different pages.
How can I solve this?
M.v.g.

**Comment by billcreswell** [comment]
The development version doesn't seem to have this issue. You can try the 4.7.4 developer release if you would like to see if that fixes it for you. (no direct upgrade available)
 https://github.com/pluck-cms/pluck/releases/tag/v4.7.4
