### ISSUE TITLE
Chmod of files & folders

### ISSUE THREAD

**Issue by 2braincells2go** [pluck-cms/pluck#37]
I noticed when installing (manually) that Pluck automatically sets many folders/files to 777. This may be fine for some but in today's world it is not. With files set to 777 it is downright dangerous and in many servers produces errors such as:

[Tue Jan 26 17:30:57.993956 2016] [:error] [pid 21603] [client 91.96.107.84:16235] SoftException in Application.cpp:256: File "/home/xxxxx/public_html/testbed/pluck/data/settings/options.php" is writeable by group

Where can I set Pluck to chmod folders/files correctly? Like 755 for folders and at most 666 (would start with 644) for files.

Many thanks in advance.

**Comment by billcreswell** [comment]
install.php contains the code that sets 777.

**Comment by billcreswell** [comment]
But you need command line access or control panel access to modify existing.
Remember that Pluck, as whatever your system runs at has to write to those files and directories.
