### ISSUE TITLE
In altervista.org

### ISSUE THREAD

**Issue by arpierm** [pluck-cms/pluck#38]
I installed pluck latest version of altrvista.org, but once installed it can not find the site and tells me http://xxxx.altervista.org/membri/xxxx/?file=home The page is not present., Where xxx 'the my site. What should I do ? Thank you

**Comment by Filisko** [comment]
Why you just don't share your link?

**Comment by arpierm** [comment]
http://pa64.altervista.org/membri/pa64/?file=home

**Comment by Filisko** [comment]
The page that appears has nothing to do with Pluck. The problem is in the host side, not Pluck.

**Comment by arpierm** [comment]
I installed the root of my web, and that should be visible at http://pa64.altervista.org/, but the CMS generates a redirect to http://pa64.altervista.org/membri/pa64/? file = home. Obviously in my web path members / PA64 does not exist, why do you see the error message.
Also specific to the full UNIX path of the root of my web is right / members / PA64.

**Comment by billcreswell** [comment]
It looks like you may have figured out what happened - (http://pa64.altervista.org/?file=home) and applied a very nice theme to it.

Let us know for the future what you discovered, and enjoy using PluckCMS!

**Comment by arpierm** [comment]
I had to change the date / inc / functions.all.php adding files below: defined ('IN_PLUCK') or exit ('Access denied!'); the following statement:
$ _SERVER ['DOCUMENT_ROOT'] = '/ members / PA64 /';
