### ISSUE TITLE
cookie law

### ISSUE THREAD

**Issue by arpierm** [pluck-cms/pluck#39]
there is a script cookie law to adapt to pluck ??

**Comment by billymail** [comment]
not currently, that's an idea.
For now, you just have to edit the theme template and put in a script like http://www.daretothink.co.uk/blog/eu-cookie-law-script/

**Comment by arpierm** [comment]
I solved this way:
1) I created a privacy page is not visible from the menu
2) I modified index.php adding <html> <head> <body> and after the <head> and before the </ head> I added the code to me by going to this link: https://silktide.com / tools / cookie-consent / download /

**Comment by billcreswell** [comment]
Excellent
