### ISSUE TITLE
Clone a blog article

### ISSUE THREAD

**Issue by musicallro** [pluck-cms/pluck#40]
I need a new modules in pluck 4.7.4  to clone a old blog article.
Is possible ?

**Comment by billcreswell** [comment]
Its not likely difficult, if I understand your request.

**Comment by musicallro** [comment]
I want to clone a blog post or page, and edit it as a new draft.

**Comment by musicallro** [comment]
Another problem with this module "BLOG" is I can't translate words " » read more" and "Pages:"
I use Romanian language but this two words appear in English. 
$lang['blog']['read_more'] = 'Mai multe detalii'; is OK in file data/modules/blog/lang/ro.php but don't appear correctly in website. 
Why ?
What changes I must to do?

**Comment by musicallro** [comment]
any help is more than welcome...

**Comment by billcreswell** [comment]
I can't imagine what this would work like, and a way it would be helpful. Are you talking about making an exact copy?

The other point you mentioned is a separate issue.

**Comment by BSteelooper** [comment]
Added this to the pull request.
