### ISSUE TITLE
Website Down - Cannot access Admin login area

### ISSUE THREAD

**Issue by ericrozet** [pluck-cms/pluck#43]
Hello...Urgent,
I just noticed our website is down. http://www.carmelvalleytennis.net.  I'm unable to pull up the Admin login page to access my website http://www.carmelvalleytennis.net/login.php. My hosting has not expired so that's not it and my domain is active till 2018. Can you please help?  You can also reach me at ericrozet@gmail.com.

Thank you,
Eric

**Comment by vavoor** [comment]
Eric,

Somethings wrong with the name server configuration since the address www.carmelvalleytennis.net cannot be resolved to an IP address and thus your website is not reachable. Please work with your Internet Service Provider to resolve the problem.

Good luck,
Gerd

**Comment by billcreswell** [comment]
It looks to me like there is a domain host parking page. If you get that resolved, and you need further help, let us know. Thanks for your help and response vavoor!
