### ISSUE TITLE
[Vulnerability] Unrestricted File Upload in background site

### ISSUE THREAD

**Issue by CodeKlaus** [pluck-cms/pluck#44]
Hi! I found a Unrestricted File Upload Vulnerability on PluckCMS 4.7.4.
I found i can bypass the filetype detection on background site by modifying the MIME type on HTTP request. And with uploading a PHP File, i can get a webshell.
![](http://ony7wielg.bkt.clouddn.com/20170412149193291619562.png)
Please fix it ASAP and contact me to get more details(i did not find you email) :
My email:codeklaus@gmail.com

**Comment by BSteelooper** [comment]
solved with pull request #54

**Comment by BSteelooper** [comment]
@codeklaus Please verify if solved.
