### ISSUE TITLE
Blog Feature: Turn off Comments

### ISSUE THREAD

**Issue by billcreswell** [pluck-cms/pluck#53]
Ability to turn off the receiving of comments on a blog post, or on the blog in general, or by date.

**Comment by arpierm** [comment]
is it possible to insert the captcha control code in the blog comments?

**Comment by BSteelooper** [comment]
I don't know if someone has made that already..

**Comment by BSteelooper** [comment]
@billcreswell is this what you are looking for? https://github.com/pluck-cms/pluck-blog-enhancements

**Comment by billcreswell** [comment]
The other person requested captcha on top of my request. Captcha, which is
evil, is implemented in that other blog app you mentioned. I just want to
turn them off, or age them off, to prevent spam without making people do
acrobatics. Moderation would be cool too.

This was just wishlist thing though

**Comment by BSteelooper** [comment]
Hi Bill,

From the readme the blog enhancements give you the yes or no reactions. The captcha is not part of it,..

`an enhancements version of blog module
Order post newest to oldest or reverse
Allow / disallow reaction per post
Edit time and date in post.
Category pages with post list
`
But I haven’t tried it so I don’t know. 

Met vriendelijke groeten/ Best regards/ Cordialement/ Mit freundlichen Grüssen/ Cumprimentos,

Bas

**Comment by BSteelooper** [comment]
@billcreswell I found in the code a reference and when I check under Options -> Module Settings --> Blog
there is an option to turn off the reactions capabilities. 
Is this what you mean?

**Comment by billcreswell** [comment]
Yes. Weird, I think I knew that.
That was easy.

**Comment by BSteelooper** [comment]
Can this issue be closed @billcreswell

**Comment by billcreswell** [comment]
Absolutely!
