### ISSUE TITLE
themes

### ISSUE THREAD

**Issue by arpierm** [pluck-cms/pluck#55]
Where can I find new themes?

**Comment by BSteelooper** [comment]
@billcreswell can you create a themes Repo? I have updated all Pluck < 4.7 themes to 4.7 and can add them to a repo.

**Comment by billcreswell** [comment]
Do you think there should be just one, or one for each?

**Comment by BSteelooper** [comment]
one should be sufficient. Only to store the theme.tar.gz files. If you need to edit / modify you just check in a complete file. 

Or I can create a folder for each theme.. and release the tars?

**Comment by BSteelooper** [comment]
Themes can be found and downloaded here: https://github.com/pluck-cms/themes
