### ISSUE TITLE
template sub sub pages

### ISSUE THREAD

**Issue by arpierm** [pluck-cms/pluck#56]
Why any template I put, I can not see the sub-sub-pages?

**Comment by BSteelooper** [comment]
You can edit the template file. in there is the option to build the menu:
for instance:
<?php theme_menu('ul', 'li', 'active', 0); ?>
will show 1 level deep.

<?php theme_menu('ul', 'li', 'active', 2); ?>
will show 2 levels deep. (pages, subpages and subsubpages> etc.

**Comment by arpierm** [comment]
you can show me an example that I am not able to use the php, thank you!

**Comment by BSteelooper** [comment]
The PHP code was not visible in the above item. Can you see it now. It is easy. 

I can also modify a template for you to add those items.

**Comment by BSteelooper** [comment]
At the moment there is not. You can use a Blog item and have the comments be your guest entries?

**Comment by BSteelooper** [comment]
You can create a category Guestbook, and make 1 blogpost in it. Then add the blog.guestbook to the page.

Otherwise a whole plugin must be made to implement this.

**Comment by arpierm** [comment]
I said if it was possible to create a Guestbook plugin starting from the blog module.

**Comment by BSteelooper** [comment]
From the blog I would not create it.. The blog is very comprehensive.

I created a Guestbook plugin from the LinkList plugin.

You can find it here: https://github.com/BSteelooper/guestbook/releases/latest

@billcreswell can you fork the linklist and guestbook to Pluck account?
