### ISSUE TITLE
updating

### ISSUE THREAD

**Issue by arpierm** [pluck-cms/pluck#57]
how do i make cms updates?

**Comment by BSteelooper** [comment]
Simply upload the new files to the server as you did the initial install.

Make sure to change the write options again as you did during install

**Comment by arpierm** [comment]
I'm sorry, but how do I know what the new files are?

**Comment by BSteelooper** [comment]
Simply overwrite all files..

When updating from before 4.7.4 dev3 first remove the tinymce folder in data/modules

After the update you have to clear the cache of your browser.
