### ISSUE TITLE
Editing Page > Pluck actions > insert file - file list is not in alphabetical order

### ISSUE THREAD

**Issue by z00m128** [pluck-cms/pluck#60]
When you have tens or hundreds files in _files_ folder, it is very hard to find needed file, when trying to add file link via _Pluck actions > insert file_ , because the file list is not in alphabetical order (like in _insert image_ function).

Is it possible to sort files in alphabetical order also in _insert file_ function, as it was in pluck's previous version?

**Comment by BSteelooper** [comment]
Hi Z00m128,

You are right. sorting is now not in the latest version. 
could you try this:
open the file data\modules\tinymce\functions.php 
on line 121 find this:
`						foreach ($files as $file) {
`
insert before the foreach: natcasesorb($files);
It should look like this:
`						natcasesort($files);
						foreach ($files as $file) {
`

Please let me know if this solved it.

Regards,
Bas

**Comment by z00m128** [comment]
Hi,
yes, this fix solved the bug. Thank you!
Regars,
z00m

**Comment by BSteelooper** [comment]
Pushed the fix to the repo.
