### ISSUE TITLE
File upload vuln pluck4.7.7

### ISSUE THREAD

**Issue by liao10086** [pluck-cms/pluck#61]
An issue was discovered in Pluck before 4.7.7. Remote PHP code execution is possible.
Do you hava a email? I send details to it.

**Comment by BSteelooper** [comment]
Is it also in the latest version?
My email is pluck[at]bas.xosc.nl

**Comment by liao10086** [comment]
author "liao"  DBAPP
I found a file upload vuln in /data/inc/images.php
line 39 .When I set my file type is image/jpg but file suffix not in $imagewhitelist ,I  can still succeed in uploading files. The line 39 judge file suffix not in $imagewhitelist,the following statements are still executed，because line 39 "if" not a nested statement。
eg:
1. Brupsuit send a image and rename
![image](https://user-images.githubusercontent.com/37523122/40776010-1bce6baa-64fc-11e8-9cb6-74e1d5f5bbb9.png)
Display upload failed but the result is upload success.
So I can uploading any file.

2.Upload new ".htaccess" to cover your ".htaccess"
I upload a php file,but it don't work.Because of the file ".hataccess",so I want to send a file cover it.
I send a image rename ".htaccess",
![image](https://user-images.githubusercontent.com/37523122/40776661-f6d50564-64fd-11e8-92f8-a146a80e5f4e.png)
When I access the "phpinfo" file is error.
So I send an effective ".htaccess" file to cover it,just like this
![image](https://user-images.githubusercontent.com/37523122/40776852-8f6d4bf6-64fe-11e8-9735-cc2a7445c02b.png)
3. upload phpinfo file
Now I send the phpinfo file by brupsuite 
![image](https://user-images.githubusercontent.com/37523122/40776976-f3e4f6ce-64fe-11e8-8e79-2a725a4a8e52.png)
clike the file ,the php code execution
![image](https://user-images.githubusercontent.com/37523122/40777044-31e406b8-64ff-11e8-9598-d8d0f558616d.png)
I hope you can fix it.
Best wishes

**Comment by BSteelooper** [comment]
I created a pre-release, can you try this?
[pluck-4.7.7-dev1.tar.gz](https://github.com/pluck-cms/pluck/files/2057825/pluck-4.7.7-dev1.tar.gz)

**Comment by BSteelooper** [comment]
Found an issue with the previous release.
Please try this one.
[pluck-4.7.7-dev2.tar.gz](https://github.com/pluck-cms/pluck/files/2057873/pluck-4.7.7-dev2.tar.gz)

**Comment by liao10086** [comment]
![image](https://user-images.githubusercontent.com/37523122/40779269-de679b0a-6506-11e8-974a-37cc7c806ff5.png)
you can fix like it

**Comment by BSteelooper** [comment]
That should be in the dev-2 version. See the second commit https://github.com/pluck-cms/pluck/commit/673d605b917db70a1134eb60385f4581e8ee3e0f

**Comment by liao10086** [comment]
oK

**Comment by BSteelooper** [comment]
The issue is confirmed.

Threat level: **LOW**
Affected: **Admin panel**

file upload: **Whitelist was not triggered properly** 

Remediation: **Updated several files**

**Solved in 4.7.7 dev 2**
