### ISSUE TITLE
garbage in newly created pages

### ISSUE THREAD

**Issue by z00m128** [pluck-cms/pluck#66]
When creating new pages or editing existing ones, some garbage is always put into body:
```
<?php
$title = 'test';
$seoname = 'test';
$content = '!DOCTYPE html
html
head
/head
body
ptest page/p
/body
/html';
$hidden = 'yes';
?>
```
Looks like tinymce is doing this. Fighting with this issue from v 4.7.6 onwards. Tried in FF, Chrome, Palemoon browsers.

**Comment by z00m128** [comment]
downgraded to 4.7.3 and its working nicely:
```
<?php
$title = 'test2';
$seoname = 'test2';
$content = '<p>test page 2</p>';
$hidden = 'yes';
?>
```

**Comment by BSteelooper** [comment]
I added one to many plugins.
Can you check the latest dev release?
[pluck-4.7.8-dev3.tar.gz](https://github.com/pluck-cms/pluck/files/2313455/pluck-4.7.8-dev3.tar.gz)

**Comment by z00m128** [comment]
Looks like it is working correctly now:
```
<?php
$title = 'test3';
$seoname = 'test3';
$content = '<p>test page 3</p>';
$hidden = 'yes';
?>
```
Thanks!

**Comment by BSteelooper** [comment]
Your Welcome,

I will prepare the production release after this weekend
