### ISSUE TITLE
[vulnerability] xss or other vulns

### ISSUE THREAD

**Issue by LLfam** [pluck-cms/pluck#77]
Hi! I think regexp in function latinOnlyInput is incorrect. So I find a xss in /data/inc/images.php line42, and I think this problem may lead to other vulnerabilities. 
In regexp, brackets have special meanings. [blank]-[underline] means blank to underline in ascii.

**Comment by BSteelooper** [comment]
<img width="514" alt="Screenshot 2019-07-17 at 19 15 35" src="https://user-images.githubusercontent.com/8290565/61396137-56d0e600-a8c7-11e9-903b-14b2b9633f97.png">

I run It trough the validator and you are correct. there is one character missing in the regexp. it should be: [^a-zA-Z0-9.\ \-_]+ (Notice the \ before the -) 
 
<img width="514" alt="Screenshot 2019-07-17 at 19 17 40" src="https://user-images.githubusercontent.com/8290565/61396254-9bf51800-a8c7-11e9-874b-758234ee6aa8.png">

**Comment by BSteelooper** [comment]
I drafted a new dev release. can you test this please? if correct I can push to production.

https://github.com/pluck-cms/pluck/releases/tag/4.7.9-dev4
[pluck-4.7.9-dev4.tar.gz](https://github.com/pluck-cms/pluck/files/3403043/pluck-4.7.9-dev4.tar.gz)

**Comment by LLfam** [comment]
Be careful in coding xD. If find other vulns, I will tell u immediately.

**Comment by BSteelooper** [comment]
Thank you. I pushed it to production. all admins will get a notification to update when they logon.
