### ISSUE TITLE
Pluck-4.7.10-dev2 admin background exists a remote command execution vulnerability when uploading files

### ISSUE THREAD

**Issue by F1sh1001** [pluck-cms/pluck#84]
This vulnerability applies to php5.2. X

![图片](https://user-images.githubusercontent.com/52944911/67195641-e092d100-f42b-11e9-9a79-20d600f7f42e.png)

After the installation is successful, go to the management background
![图片](https://user-images.githubusercontent.com/52944911/67195698-01f3bd00-f42c-11e9-99c5-8d9553ad5631.png)

Then upload shell.php, It will be changed to shell.php.txt

![图片](https://user-images.githubusercontent.com/52944911/67195737-1768e700-f42c-11e9-8913-a287f77b5e4f.png)

Then upload shell.php again

![图片](https://user-images.githubusercontent.com/52944911/67195913-6d3d8f00-f42c-11e9-9c01-dbc24462fb4f.png)

Shell.php has not been changed to shell.php.txt

![图片](https://user-images.githubusercontent.com/52944911/67196467-71b67780-f42d-11e9-9cf6-c36cae289a25.png)

then view shell.php

![图片](https://user-images.githubusercontent.com/52944911/67201439-e7741080-f438-11e9-987b-ea86793f0810.png)

**Comment by BSteelooper** [comment]
As you state this is an issue with php 5.2.x this doesn't exist in php7. php5 is not longer supported by php (see https://www.php.net/supported-versions.php) and we cannot maintain versions which are no longer supported. 

I have updated the minimal requirements to version 7  but it will work so I included a warning message that an insecure php version is used. 

Will be in the next release
