### ISSUE TITLE
Pluck-4.7.10 admin background exists a remote command execution vulnerability 

### ISSUE THREAD

**Issue by 2A806** [pluck-cms/pluck#86]
Pluck-4.7.10 admin background exists a remote command execution vulnerability 

it happens when restore file from trashcan,and the restoring file has the same with one of the files in uploaded files dir
the coding flaw is in file /pluck/data/inc/trashcan_restoreitem.php at line 54 
![image](https://user-images.githubusercontent.com/40019435/67352642-1e563d80-f583-11e9-8eeb-f478925ede76.png)
when $var1 is 'shell.php.txt', here $filename will get value 'shell' and $extension will get value 'php', and then concat with the string '_copy' we will get the final filename with 'shell_copy.php'

Proof
step1: login -> pages -> manage files
upload file with name shell.php.txt
![image](https://user-images.githubusercontent.com/40019435/67352907-dab00380-f583-11e9-8a69-f926062a0a47.png)
![image](https://user-images.githubusercontent.com/40019435/67352918-e0a5e480-f583-11e9-9770-8d9785953a76.png)
upload success
![image](https://user-images.githubusercontent.com/40019435/67352973-0501c100-f584-11e9-8eee-15b78dc17236.png)

step2: delete file to trashcan
![image](https://user-images.githubusercontent.com/40019435/67353027-2367bc80-f584-11e9-86a4-3b5acbdbd91a.png)

step3: upload the same file again
![image](https://user-images.githubusercontent.com/40019435/67353068-3b3f4080-f584-11e9-92b6-f9c3a739a065.png)

step4: restore the file from trashcan, and the restored file is renamed as shell_copy.php
![image](https://user-images.githubusercontent.com/40019435/67353127-66299480-f584-11e9-84ac-643a2d59bff2.png)
![image](https://user-images.githubusercontent.com/40019435/67353191-9a9d5080-f584-11e9-8167-77432492d8ef.png)

step5: visit webshell
![image](https://user-images.githubusercontent.com/40019435/67353223-abe65d00-f584-11e9-8d51-8f14f4c0f666.png)

note: operate with "manage images" can do the same as it has the same coding flaw at line 76

**Comment by BSteelooper** [comment]
I drafted a new release : https://github.com/pluck-cms/pluck/releases/tag/4.7.10-dev5
Could you please retest?

**Comment by BSteelooper** [comment]
There is a typeerror that there is a . added to the end of the line. This is resolved in repo but didn't get into the release. it will be in the next one.

**Comment by 2A806** [comment]
![image](https://user-images.githubusercontent.com/40019435/67360990-f920f980-f599-11e9-9bbf-5d1d6c970249.png)
you should remove this too.
