### ISSUE TITLE
Pluck-4.7.11 admin background exists a remote command execution vulnerability when uploading files

### ISSUE THREAD

**Issue by wooyin** [pluck-cms/pluck#90]
After the installation is successful, go to the management background
![图片](https://user-images.githubusercontent.com/48854942/71102923-3ac5cd80-21f4-11ea-8267-d134c857ea15.png)
Then upload images.zip
![图片](https://user-images.githubusercontent.com/48854942/71103572-5382b300-21f5-11ea-91d5-51b4542d1868.png)
![图片](https://user-images.githubusercontent.com/48854942/71103633-672e1980-21f5-11ea-9dc4-0ed778f98f86.png)
![图片](https://user-images.githubusercontent.com/48854942/71104763-4b2b7780-21f7-11ea-84cb-8eab9b5cf540.png)
then view file to execute command
![图片](https://user-images.githubusercontent.com/48854942/71103671-7614cc00-21f5-11ea-9fc4-e1d86263291b.png)

**Comment by BSteelooper** [comment]
Duplicate off issue #75
