### ISSUE TITLE
Pluck v4.7.11 Issue 

### ISSUE THREAD

**Issue by wooyin** [pluck-cms/pluck#92]
Step1: pages - new page - save and exit

![图片](https://user-images.githubusercontent.com/48854942/71189128-44673800-22bd-11ea-8a19-5dd671ed40c4.png)

Step1: change seo_name like "seo_name=...................."

![图片](https://user-images.githubusercontent.com/48854942/71188831-a7a49a80-22bc-11ea-9f41-5dca8ee5e167.png)

```
POST /pluck4711/admin.php?action=editpage HTTP/1.1
Host: 192.168.1.23
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Referer: http://192.168.1.23/pluck4711/admin.php?action=editpage
Content-Type: application/x-www-form-urlencoded
Content-Length: 148
DNT: 1
Connection: close
Cookie: PHPSESSID=b742v7duoaihe7e5lrfh365597
Upgrade-Insecure-Requests: 1

title=1112312312311&seo_name=....................&content=123132132&description=&keywords=&hidden=no&sub_page=&theme=default&save_exit=Save+and+Exit
```

step3: the website can not reload 
![图片](https://user-images.githubusercontent.com/48854942/71188803-9bb8d880-22bc-11ea-9619-de7e662c8492.png)

data/settings/pages
![图片](https://user-images.githubusercontent.com/48854942/71188868-ba1ed400-22bc-11ea-822e-de152aa71745.png)

**Comment by BSteelooper** [comment]
Could you do a retest with version: https://github.com/pluck-cms/pluck/tree/4.7.12-dev2

**Comment by wooyin** [comment]
This one is resolved

**Comment by BSteelooper** [comment]
Nice, thank you for the feedback
