### ISSUE TITLE
[HELP] Upgrade/backup from old version

### ISSUE THREAD

**Issue by forart** [pluck-cms/pluck#93]
Hi everyone, we're old Pluck users and we wanna upgrade our ODFAS project site (including settings, theme, pages, files, etc.): http://www.forart.it/progetti/ODFAS/

The site is now managed by Super Pluck Power Pack 4.6.4 but we can't undestand if is safe to just overwrite files or is better to backup and re-install.

Thanks in advice to anyone will help.

FORART NPO

**Comment by BSteelooper** [comment]
I don't know which modules your are using, also there might be some changes to your theme necessary. There is in the docs folder of each version an upgrade.php which does upgrade the pages and some default modules.

Some testing might be required. if you need assistance I am able to help some

**Comment by forart** [comment]
Sorry but the new Pluck 4.7.x version puts me in total confusion.

I've tried to install it in another folder and just adding old files but the result is:
http://www.forart.it/progetti/ODFASnew/

About theme: how to change it theme ?

Modules: how (and where) to download/install modules easily ?

**Comment by BSteelooper** [comment]
In the docs folder is a file update.php. you have to copy this to the root and run this. 
if you copied the data\settings folder and the data\modules data\themes folder over it will run through this. 
After this you might have to update some files for the theme and modules

**Comment by BSteelooper** [comment]
Download modules: in the https://github.com/pluck-cms there are several modules which are ready for 4.7
I modified some 4.6 themes to 4.7 you can find them her https://github.com/pluck-cms/themes

When you go to options, you can upload modules and themes

**Comment by forart** [comment]
> In the docs folder is a file update.php. you have to copy this to the root and run this.
I tried on the old installation but says "Access denied!":
http://www.forart.it/progetti/ODFAS/update.php

> Download modules: in the https://github.com/pluck-cms there are several modules which are ready for 4.7
Well, of course, but i tried to install the "pluck-backup-master.zip" and the result is:
"Warning: call_user_func() expects parameter 1 to be a valid callback, function 'pluck-backup-master_info' not found or invalid function name in /web/htdocs/www.forart.it/home/progetti/ODFASnew/data/inc/modules_manage.php on line 32

pluck-backup-master - This module is not compatible with your version of pluck, and has been disabled."

I'm still confused.

> I modified some 4.6 themes to 4.7 you can find them her https://github.com/pluck-cms/themes
> 
> When you go to options, you can upload modules and themes

**Comment by BSteelooper** [comment]
The module manager requires the tar.gz extension There should be a release which you can use. eg: https://github.com/pluck-cms/pluck-backup/tree/0.9 
There was no release so I drafted it for you

**Comment by forart** [comment]
OK, meanwhile I tried to install - after another complete reinstall of latest Pluck (count: 5) - some themes and nothing shows.

Here's how Zenlinke appear:
http://www.forart.it/progetti/ODFASnew/

OMG, what'a appened to Pluck ?

**Comment by BSteelooper** [comment]
Version 4.7 was released in 2014, and since than we had several security issues which needed to be addressed, and also had some compatibility issues with browsers which led to some upgrades..

The WYSIWYG editor has been updated and instead of the insertion of modules/pages/images/files from the right hand side, has this been added to the menu of the editor under Pluck Actions. 

You write, nothing shows. Which PHP Version are you using? 
Have you taken the zenlike from the GitHub cache?

**Comment by BSteelooper** [comment]
> OK, meanwhile I succesfully installed - after another complete delete, reupload and install of latest Pluck (count: 5) - some themes and nothing shows.
> 
> OMG, what'a happened to Pluck ?

I found an issue with an update which was performed on the editor, which only affects new installs.

I created a new Release, could you test this version please?

**Comment by miwebguy** [comment]
http://www.forart.it/progetti/?file=ODFASnew
http://www.forart.it/progetti/?file=ODFAS

I think it's htaccess/url redirect that's at issue

**Comment by BSteelooper** [comment]
> http://www.forart.it/progetti/?file=ODFASnew
> http://www.forart.it/progetti/?file=ODFAS
> 
> I think it's htaccess/url redirect that's at issue

There is no htaccess or redirect in the standard Pluck setup. What is in that file?
The link you provide I can enter anything and still have the same site.. (http://www.forart.it/progetti/?file=asdasdads gives me the same site)

The website http://www.forart.it/progetti/ODFAS is the old install of pluck.

**Comment by forart** [comment]
Sorry for the delay guyz, but i'm very busy with my work.

OK, I tested (again) the 4.7.13 version, and here's the result (Zenlike theme): http://www.forart.it/test/PLUCKnew/

The problem may be that my webprovider - aruba.it - don't allow "777" permissions (even if they claim that server treat 755 such as 777).

But I honestly don't understand what differences produces these results.

I'll try the new version on another wsp as soon as I can.

**Comment by BSteelooper** [comment]
Since accessing the style.css generates an Error 500 there must be something wrong in the installation location. Are there any .htaccess files in the path? For instance the root or test..

I don’t know if you have access to your own sites error.log file (might be in a log folder outside the public_html folder) 
That logfile might give a clue.

![02771D1A-AEF5-46FE-90E6-8876EC9987E9](https://user-images.githubusercontent.com/8290565/74155316-ac2e6500-4c14-11ea-96aa-2af563df002f.jpeg)

**Comment by BSteelooper** [comment]
Do you have looked into this error 500? do you still need assistance?

**Comment by forart** [comment]
Sorry but I haven't tried again. I'll do as soon as possible.

**Comment by forart** [comment]
Ok, I just discovered that my Hosting provider serves installations for many CMS (Pluck too !) by Softaculous 5.3.9

Here's the result: http://www.forart.it/pluck/

**Comment by millerebonds** [comment]
Hello,
I tried to put the update.php on the root, and try to update. It wants to update to the same 4.7.3 version…

What must I do to update my website without to reinstall pluck?

**Comment by BSteelooper** [comment]
> Hello,
> I tried to put the update.php which is in doc folder on the root, and tried to update. It wants to update to the same 4.7.3 version…
> 
> What must I do to update my website without to reinstall pluck?

The 4.7 versions are easy updateable By simply downloading the new version and overwriting all the files. 
The update.php is to update from the 4.6 version

You can also install the updated module and update with that.

**Comment by millerebonds** [comment]
Hello, I downloaded and overwrote all the files.
It works!

I have just this comment: "You PHP version is to low and your installation might be at risk"

The problem comes from my hosting ?   (it's possible)

**Comment by millerebonds** [comment]
Thank you!

**Comment by BSteelooper** [comment]
> Hello, I downloaded and overwrote all the files.
> It works!
> 
> I have just this comment: "You PHP version is to low and your installation might be at risk"
> 
> The problem comes from my hosting ? (it's possible)

I think it is. Sometimes you have the option to select the php version for your website. If so select the highest possible number, preferably 7.4 which is the current highest version.
If you have php5 or php7.0 there might be issues in php which are not being fixed anymore. That is what the warning is for.
