### ISSUE TITLE
XSS vulnerable

### ISSUE THREAD

**Issue by Any3ite** [pluck-cms/pluck#95]
XSS cross site vulnerability can occur during installation
1. 
![111](https://user-images.githubusercontent.com/20638313/75873308-ab22d900-5e4a-11ea-8c50-c1f04f265924.jpg)

2. 
![2](https://user-images.githubusercontent.com/20638313/75873370-bb3ab880-5e4a-11ea-8774-4e7aee3f3455.jpg)

**Comment by BSteelooper** [comment]
This is not a XXS bug. This is simply entering html tags in a web page. this will be possible in all content management systems.
